$content = Get-Content 'vanData.js' -Raw -Encoding UTF8

$n2vocaBlock = @'
, n2voca: {
    struct: [
        {
            name: "Bài 1 (1-50)",
            free: true,
            list: [
                { c1: "以外", c2: "いがい", c3: "ngoài ra, trừ", c4: "", c5: "", c6: "", count: 0 },
                { c1: "以降", c2: "いこう", c3: "từ sau, kể từ", c4: "", c5: "", c6: "", count: 0 },
                { c1: "意外", c2: "いがい", c3: "bất ngờ", c4: "", c5: "", c6: "", count: 0 },
                { c1: "一般", c2: "いっぱん", c3: "nói chung, phổ biến", c4: "", c5: "", c6: "", count: 0 },
                { c1: "印象", c2: "いんしょう", c3: "ấn tượng", c4: "", c5: "", c6: "", count: 0 },
                { c1: "影響", c2: "えいきょう", c3: "ảnh hưởng", c4: "", c5: "", c6: "", count: 0 },
                { c1: "永遠", c2: "えいえん", c3: "vĩnh cửu", c4: "", c5: "", c6: "", count: 0 },
                { c1: "延長", c2: "えんちょう", c3: "kéo dài, mở rộng", c4: "", c5: "", c6: "", count: 0 },
                { c1: "応援", c2: "おうえん", c3: "cổ vũ, ủng hộ", c4: "", c5: "", c6: "", count: 0 },
                { c1: "応用", c2: "おうよう", c3: "ứng dụng", c4: "", c5: "", c6: "", count: 0 },
                { c1: "大げさ", c2: "おおげさ", c3: "cường điệu, phóng đại", c4: "", c5: "", c6: "", count: 0 },
                { c1: "大幅", c2: "おおはば", c3: "lớn, đáng kể", c4: "", c5: "", c6: "", count: 0 },
                { c1: "思いがけない", c2: "おもいがけない", c3: "không ngờ tới", c4: "", c5: "", c6: "", count: 0 },
                { c1: "改正", c2: "かいせい", c3: "cải chính, sửa đổi", c4: "", c5: "", c6: "", count: 0 },
                { c1: "解消", c2: "かいしょう", c3: "giải quyết, giải tán", c4: "", c5: "", c6: "", count: 0 },
                { c1: "確認", c2: "かくにん", c3: "xác nhận", c4: "", c5: "", c6: "", count: 0 },
                { c1: "格差", c2: "かくさ", c3: "chênh lệch", c4: "", c5: "", c6: "", count: 0 },
                { c1: "活躍", c2: "かつやく", c3: "hoạt động tích cực", c4: "", c5: "", c6: "", count: 0 },
                { c1: "必ず", c2: "かならず", c3: "nhất định, chắc chắn", c4: "", c5: "", c6: "", count: 0 },
                { c1: "観察", c2: "かんさつ", c3: "quan sát", c4: "", c5: "", c6: "", count: 0 },
                { c1: "完成", c2: "かんせい", c3: "hoàn thành", c4: "", c5: "", c6: "", count: 0 },
                { c1: "管理", c2: "かんり", c3: "quản lý", c4: "", c5: "", c6: "", count: 0 },
                { c1: "基本", c2: "きほん", c3: "cơ bản", c4: "", c5: "", c6: "", count: 0 },
                { c1: "記録", c2: "きろく", c3: "ghi chép, kỷ lục", c4: "", c5: "", c6: "", count: 0 },
                { c1: "規則", c2: "きそく", c3: "quy tắc, quy định", c4: "", c5: "", c6: "", count: 0 },
                { c1: "機能", c2: "きのう", c3: "chức năng", c4: "", c5: "", c6: "", count: 0 },
                { c1: "義務", c2: "ぎむ", c3: "nghĩa vụ", c4: "", c5: "", c6: "", count: 0 },
                { c1: "逆", c2: "ぎゃく", c3: "ngược lại", c4: "", c5: "", c6: "", count: 0 },
                { c1: "共通", c2: "きょうつう", c3: "chung, phổ biến", c4: "", c5: "", c6: "", count: 0 },
                { c1: "具体的", c2: "ぐたいてき", c3: "cụ thể", c4: "", c5: "", c6: "", count: 0 },
                { c1: "経験", c2: "けいけん", c3: "kinh nghiệm", c4: "", c5: "", c6: "", count: 0 },
                { c1: "結果", c2: "けっか", c3: "kết quả", c4: "", c5: "", c6: "", count: 0 },
                { c1: "欠点", c2: "けってん", c3: "nhược điểm", c4: "", c5: "", c6: "", count: 0 },
                { c1: "原因", c2: "げんいん", c3: "nguyên nhân", c4: "", c5: "", c6: "", count: 0 },
                { c1: "現状", c2: "げんじょう", c3: "hiện trạng", c4: "", c5: "", c6: "", count: 0 },
                { c1: "効果", c2: "こうか", c3: "hiệu quả", c4: "", c5: "", c6: "", count: 0 },
                { c1: "行動", c2: "こうどう", c3: "hành động", c4: "", c5: "", c6: "", count: 0 },
                { c1: "合理的", c2: "ごうりてき", c3: "hợp lý", c4: "", c5: "", c6: "", count: 0 },
                { c1: "個人", c2: "こじん", c3: "cá nhân", c4: "", c5: "", c6: "", count: 0 },
                { c1: "根拠", c2: "こんきょ", c3: "cơ sở, căn cứ", c4: "", c5: "", c6: "", count: 0 },
                { c1: "混乱", c2: "こんらん", c3: "hỗn loạn", c4: "", c5: "", c6: "", count: 0 },
                { c1: "最終", c2: "さいしゅう", c3: "cuối cùng", c4: "", c5: "", c6: "", count: 0 },
                { c1: "作業", c2: "さぎょう", c3: "công việc, thao tác", c4: "", c5: "", c6: "", count: 0 },
                { c1: "差別", c2: "さべつ", c3: "phân biệt đối xử", c4: "", c5: "", c6: "", count: 0 },
                { c1: "実感", c2: "じっかん", c3: "cảm nhận thực tế", c4: "", c5: "", c6: "", count: 0 },
                { c1: "実施", c2: "じっし", c3: "thực thi, tiến hành", c4: "", c5: "", c6: "", count: 0 },
                { c1: "実態", c2: "じったい", c3: "thực trạng", c4: "", c5: "", c6: "", count: 0 },
                { c1: "実力", c2: "じつりょく", c3: "thực lực, năng lực thật", c4: "", c5: "", c6: "", count: 0 },
                { c1: "主張", c2: "しゅちょう", c3: "chủ trương, khẳng định", c4: "", c5: "", c6: "", count: 0 },
                { c1: "重要", c2: "じゅうよう", c3: "quan trọng", c4: "", c5: "", c6: "", count: 0 }
            ]
        },
        {
            name: "Bài 2 (51-100)",
            free: true,
            list: [
                { c1: "順番", c2: "じゅんばん", c3: "thứ tự", c4: "", c5: "", c6: "", count: 0 },
                { c1: "状況", c2: "じょうきょう", c3: "tình hình", c4: "", c5: "", c6: "", count: 0 },
                { c1: "証明", c2: "しょうめい", c3: "chứng minh", c4: "", c5: "", c6: "", count: 0 },
                { c1: "正確", c2: "せいかく", c3: "chính xác", c4: "", c5: "", c6: "", count: 0 },
                { c1: "成功", c2: "せいこう", c3: "thành công", c4: "", c5: "", c6: "", count: 0 },
                { c1: "精神", c2: "せいしん", c3: "tinh thần", c4: "", c5: "", c6: "", count: 0 },
                { c1: "責任", c2: "せきにん", c3: "trách nhiệm", c4: "", c5: "", c6: "", count: 0 },
                { c1: "積極的", c2: "せっきょくてき", c3: "tích cực", c4: "", c5: "", c6: "", count: 0 },
                { c1: "設備", c2: "せつび", c3: "thiết bị, cơ sở vật chất", c4: "", c5: "", c6: "", count: 0 },
                { c1: "全体", c2: "ぜんたい", c3: "toàn thể", c4: "", c5: "", c6: "", count: 0 },
                { c1: "想像", c2: "そうぞう", c3: "tưởng tượng", c4: "", c5: "", c6: "", count: 0 },
                { c1: "尊重", c2: "そんちょう", c3: "tôn trọng", c4: "", c5: "", c6: "", count: 0 },
                { c1: "対応", c2: "たいおう", c3: "đối ứng, xử lý", c4: "", c5: "", c6: "", count: 0 },
                { c1: "対象", c2: "たいしょう", c3: "đối tượng", c4: "", c5: "", c6: "", count: 0 },
                { c1: "達成", c2: "たっせい", c3: "đạt được, hoàn thành", c4: "", c5: "", c6: "", count: 0 },
                { c1: "担当", c2: "たんとう", c3: "phụ trách", c4: "", c5: "", c6: "", count: 0 },
                { c1: "単純", c2: "たんじゅん", c3: "đơn giản", c4: "", c5: "", c6: "", count: 0 },
                { c1: "知識", c2: "ちしき", c3: "kiến thức", c4: "", c5: "", c6: "", count: 0 },
                { c1: "挑戦", c2: "ちょうせん", c3: "thách thức, thử sức", c4: "", c5: "", c6: "", count: 0 },
                { c1: "調査", c2: "ちょうさ", c3: "điều tra, khảo sát", c4: "", c5: "", c6: "", count: 0 },
                { c1: "直接", c2: "ちょくせつ", c3: "trực tiếp", c4: "", c5: "", c6: "", count: 0 },
                { c1: "通常", c2: "つうじょう", c3: "thông thường", c4: "", c5: "", c6: "", count: 0 },
                { c1: "提案", c2: "ていあん", c3: "đề xuất", c4: "", c5: "", c6: "", count: 0 },
                { c1: "適切", c2: "てきせつ", c3: "phù hợp, thích hợp", c4: "", c5: "", c6: "", count: 0 },
                { c1: "展開", c2: "てんかい", c3: "triển khai, mở rộng", c4: "", c5: "", c6: "", count: 0 },
                { c1: "当然", c2: "とうぜん", c3: "đương nhiên", c4: "", c5: "", c6: "", count: 0 },
                { c1: "特徴", c2: "とくちょう", c3: "đặc điểm, đặc trưng", c4: "", c5: "", c6: "", count: 0 },
                { c1: "独自", c2: "どくじ", c3: "độc đáo, riêng biệt", c4: "", c5: "", c6: "", count: 0 },
                { c1: "内容", c2: "ないよう", c3: "nội dung", c4: "", c5: "", c6: "", count: 0 },
                { c1: "認識", c2: "にんしき", c3: "nhận thức", c4: "", c5: "", c6: "", count: 0 },
                { c1: "能力", c2: "のうりょく", c3: "năng lực", c4: "", c5: "", c6: "", count: 0 },
                { c1: "判断", c2: "はんだん", c3: "phán đoán", c4: "", c5: "", c6: "", count: 0 },
                { c1: "批判", c2: "ひはん", c3: "phê bình, chỉ trích", c4: "", c5: "", c6: "", count: 0 },
                { c1: "表現", c2: "ひょうげん", c3: "biểu đạt, diễn đạt", c4: "", c5: "", c6: "", count: 0 },
                { c1: "変化", c2: "へんか", c3: "biến đổi", c4: "", c5: "", c6: "", count: 0 },
                { c1: "方針", c2: "ほうしん", c3: "phương châm, đường lối", c4: "", c5: "", c6: "", count: 0 },
                { c1: "本質", c2: "ほんしつ", c3: "bản chất", c4: "", c5: "", c6: "", count: 0 },
                { c1: "目標", c2: "もくひょう", c3: "mục tiêu", c4: "", c5: "", c6: "", count: 0 },
                { c1: "役割", c2: "やくわり", c3: "vai trò", c4: "", c5: "", c6: "", count: 0 },
                { c1: "要因", c2: "よういん", c3: "nhân tố, yếu tố", c4: "", c5: "", c6: "", count: 0 },
                { c1: "予測", c2: "よそく", c3: "dự đoán", c4: "", c5: "", c6: "", count: 0 },
                { c1: "理解", c2: "りかい", c3: "hiểu, thông cảm", c4: "", c5: "", c6: "", count: 0 },
                { c1: "理由", c2: "りゆう", c3: "lý do", c4: "", c5: "", c6: "", count: 0 },
                { c1: "利用", c2: "りよう", c3: "sử dụng, tận dụng", c4: "", c5: "", c6: "", count: 0 },
                { c1: "論理", c2: "ろんり", c3: "logic, luận lý", c4: "", c5: "", c6: "", count: 0 },
                { c1: "割合", c2: "わりあい", c3: "tỷ lệ", c4: "", c5: "", c6: "", count: 0 },
                { c1: "円滑", c2: "えんかつ", c3: "suôn sẻ, trơn tru", c4: "", c5: "", c6: "", count: 0 },
                { c1: "課題", c2: "かだい", c3: "nhiệm vụ, vấn đề cần giải quyết", c4: "", c5: "", c6: "", count: 0 },
                { c1: "過程", c2: "かてい", c3: "quá trình", c4: "", c5: "", c6: "", count: 0 },
                { c1: "価値観", c2: "かちかん", c3: "quan niệm giá trị", c4: "", c5: "", c6: "", count: 0 }
            ]
        }
    ],
    quiz: [
        {
            name: "Bài 1 (Câu 1-20)",
            free: true,
            list: [
                { gramType: "quiz", q: "彼女は試験に( ________)、家族みんなで喜んだ。", ans: "合格して", w1: "失格して", w2: "不合格で", w3: "落第して", explain: "「合格する（ごうかくする）」＝ đậu thi → Dịch: Cô ấy đậu kỳ thi, cả gia đình vui mừng", count: 0 },
                { gramType: "quiz", q: "計画を( ________)に進めるために、全員で協力した。", ans: "円滑", w1: "困難", w2: "複雑", w3: "混乱", explain: "「円滑（えんかつ）」＝ suôn sẻ → Dịch: Để thực hiện kế hoạch suôn sẻ, mọi người cùng hợp tác", count: 0 },
                { gramType: "quiz", q: "この問題の( ________)をはっきりさせる必要がある。", ans: "原因", w1: "結果", w2: "効果", w3: "目標", explain: "「原因（げんいん）」＝ nguyên nhân → Dịch: Cần làm rõ nguyên nhân của vấn đề này", count: 0 },
                { gramType: "quiz", q: "彼は困難な状況でも( ________)的に取り組んだ。", ans: "積極", w1: "消極", w2: "否定", w3: "受動", explain: "「積極的（せっきょくてき）」＝ tích cực → Dịch: Anh ấy đối mặt tích cực dù hoàn cảnh khó khăn", count: 0 },
                { gramType: "quiz", q: "新しいシステムを( ________)するには時間がかかる。", ans: "導入", w1: "廃止", w2: "縮小", w3: "停止", explain: "「導入（どうにゅう）」＝ đưa vào áp dụng → Dịch: Cần thời gian để áp dụng hệ thống mới", count: 0 },
                { gramType: "quiz", q: "詳しい( ________)については担当者にお問い合わせください。", ans: "内容", w1: "外見", w2: "形式", w3: "数量", explain: "「内容（ないよう）」＝ nội dung → Dịch: Về nội dung chi tiết, vui lòng liên hệ người phụ trách", count: 0 },
                { gramType: "quiz", q: "プロジェクトの( ________)を全員で確認した。", ans: "目標", w1: "障害", w2: "失敗", w3: "終了", explain: "「目標（もくひょう）」＝ mục tiêu → Dịch: Cả nhóm xác nhận mục tiêu của dự án", count: 0 },
                { gramType: "quiz", q: "状況の変化に( ________)して対応することが大切だ。", ans: "柔軟", w1: "頑固", w2: "固定", w3: "硬直", explain: "「柔軟（じゅうなん）」＝ linh hoạt → Dịch: Quan trọng là linh hoạt ứng phó với biến đổi", count: 0 },
                { gramType: "quiz", q: "科学の( ________)により、生活が便利になった。", ans: "発展", w1: "衰退", w2: "停止", w3: "後退", explain: "「発展（はってん）」＝ phát triển → Dịch: Nhờ phát triển khoa học, cuộc sống tiện lợi hơn", count: 0 },
                { gramType: "quiz", q: "彼女は仕事に( ________)を持って取り組んでいる。", ans: "責任感", w1: "無責任", w2: "他人任せ", w3: "無関心", explain: "「責任感（せきにんかん）」＝ ý thức trách nhiệm → Dịch: Cô ấy làm việc với tinh thần trách nhiệm cao", count: 0 },
                { gramType: "quiz", q: "問題を解決するための( ________)を話し合った。", ans: "方策", w1: "障害", w2: "困難", w3: "失敗", explain: "「方策（ほうさく）」＝ biện pháp → Dịch: Thảo luận về biện pháp giải quyết vấn đề", count: 0 },
                { gramType: "quiz", q: "このデータは( ________)に基づいている。", ans: "事実", w1: "想像", w2: "推測", w3: "希望", explain: "「事実（じじつ）」＝ sự thật → Dịch: Dữ liệu này dựa trên sự thật", count: 0 },
                { gramType: "quiz", q: "彼は自分の( ________)を信じて挑戦した。", ans: "実力", w1: "弱点", w2: "限界", w3: "欠点", explain: "「実力（じつりょく）」＝ thực lực → Dịch: Anh ấy tin vào thực lực của mình và thử sức", count: 0 },
                { gramType: "quiz", q: "チームの( ________)を高めるために勉強会を開いた。", ans: "能力", w1: "無能", w2: "限界", w3: "欠如", explain: "「能力（のうりょく）」＝ năng lực → Dịch: Tổ chức buổi học để nâng cao năng lực của nhóm", count: 0 },
                { gramType: "quiz", q: "社会の( ________)に合わせてルールを変える必要がある。", ans: "変化", w1: "停止", w2: "固定", w3: "終了", explain: "「変化（へんか）」＝ biến đổi → Dịch: Cần thay đổi quy tắc phù hợp với biến đổi xã hội", count: 0 },
                { gramType: "quiz", q: "会議では自分の( ________)をはっきり伝えることが重要だ。", ans: "主張", w1: "遠慮", w2: "沈黙", w3: "服従", explain: "「主張（しゅちょう）」＝ chủ trương, ý kiến → Dịch: Trong họp, quan trọng là nêu rõ ý kiến của mình", count: 0 },
                { gramType: "quiz", q: "この研究の( ________)が明らかになった。", ans: "成果", w1: "失敗", w2: "限界", w3: "欠陥", explain: "「成果（せいか）」＝ kết quả, thành tựu → Dịch: Kết quả của nghiên cứu này đã được làm rõ", count: 0 },
                { gramType: "quiz", q: "彼の( ________)は非常に優れている。", ans: "判断力", w1: "感情", w2: "記憶力", w3: "体力", explain: "「判断力（はんだんりょく）」＝ khả năng phán đoán → Dịch: Khả năng phán đoán của anh ấy rất xuất sắc", count: 0 },
                { gramType: "quiz", q: "この計画を( ________)するには多くの課題がある。", ans: "実現", w1: "中止", w2: "廃止", w3: "削除", explain: "「実現（じつげん）」＝ thực hiện, hiện thực hóa → Dịch: Có nhiều vấn đề cần giải quyết để thực hiện kế hoạch này", count: 0 },
                { gramType: "quiz", q: "彼女は自分の( ________)を大切にして生きている。", ans: "価値観", w1: "外見", w2: "地位", w3: "財産", explain: "「価値観（かちかん）」＝ quan niệm giá trị → Dịch: Cô ấy sống trân trọng quan niệm giá trị của mình", count: 0 }
            ]
        }
    ]
}
'@

# Replace pattern: end of n1voca block before n2gram
$content = $content -replace '(\s*\]\s*\}\s*), n2gram:', "$1$n2vocaBlock, n2gram:"

Set-Content 'vanData.js' $content -Encoding UTF8 -NoNewline
Write-Host "Done! n2voca inserted successfully."
